sudo: required
services:
  - docker
before_install:
  - docker pull yglukhov/devel
script:
  - docker run -v "$(pwd):/project" -w /project yglukhov/devel run "nimble install -y && nim tests nimx.nims"
  - ./deployGHPages.sh ./doc
